### ISSUE TITLE
Have missing some strings

### ISSUE THREAD

**Issue by aniol** [iliasbartolini/the-internet-s-own-boy--aaron-swartz--subtitles#10]
In the new version are missing the first strings like "Unjust laws exist...".

**Comment by iliasbartolini** [comment]
Hi aniol,
This ticket is very old, I'm just leaving here a brief explanation before closing it.

Having that section in the subtitles would be more convenient for translators: that's why I initially I put the text there.
On the other side, for people who want to see the film with EN subtitles it is confusing to see the text repeated in the subtitles when is already in the video. 

For this reason I accepted an old pull request that removed that:
https://github.com/iliasbartolini/the-internet-s-own-boy--aaron-swartz--subtitles/commit/460191e7ae59e2fbb290388ac192f488837c2e35#diff-6acf55f1d333bde474894a28aa234b78 

Despite long time has passed: thank you for raising and asking this. 
I just lost it in my inbox and never came back to properly give an answer.
